---
general:
  buildTool: 'npm'
service:
  buildToolVersion: 'N16'
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Acceptance:
    cloudFoundryDeploy: false
    uiVeri5ExecuteTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: false
    cfApiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
    cfOrg: 'e329105ftrial'
    cfSpace: 'dev'
    cfAppName: 'Demo'
    cfCredentialsId: 'cfdeploy'
    tmsUpload: false
steps:
  artifactPrepareVersion:
    versioningType: 'cloud_noTag'
  cloudFoundryDeploy:
    mtaDeployParameters: '-f --version-rule ALL'
